import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Cormorant_Garamond, JetBrains_Mono } from "next/font/google";
import { ConditionalHeader } from "@/components/conditional-header";
import "./globals.css";

const cormorant = Cormorant_Garamond({
  subsets: ["latin"],
  variable: "--font-cormorant",
  weight: ["400", "600", "700"],
});

const jetbrains = JetBrains_Mono({
  subsets: ["latin"],
  variable: "--font-jetbrains",
});

export const metadata: Metadata = {
  title: "DeepSearch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInFallbackRedirectUrl="/chat"
      signUpFallbackRedirectUrl="/chat"
    >
      <html lang="en">
        <body
          className={`${cormorant.variable} ${jetbrains.variable} antialiased font-sans`}
        >
          <ConditionalHeader>{children}</ConditionalHeader>
        </body>
      </html>
    </ClerkProvider>
  );
}
