import { type Metadata } from "next";
import { ClerkProvider } from "@clerk/nextjs";
import { Syne, Outfit } from "next/font/google";
import { ConditionalHeader } from "@/components/conditional-header";
import "./globals.css";

const syne = Syne({
  subsets: ["latin"],
  variable: "--font-syne",
});

const outfit = Outfit({
  subsets: ["latin"],
  variable: "--font-outfit",
});

export const metadata: Metadata = {
  title: "DeepSearch",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      signInFallbackRedirectUrl="/chat"
      signUpFallbackRedirectUrl="/chat"
    >
      <html lang="en">
        <body
          className={`${syne.variable} ${outfit.variable} antialiased font-sans`}
        >
          <ConditionalHeader>{children}</ConditionalHeader>
        </body>
      </html>
    </ClerkProvider>
  );
}
