name: Gemini PR Review

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  run-gemini:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      
      - name: Run Gemini CLI
        uses: google-github-actions/run-gemini-cli@v0.1.14